---
- fail:
    msg: "Please fill in the details in vars/main.yml"
  when: GITHUB_API_KEY == "fill_me_in" or repo.owner == "insert_username_here" or repo.name == "insert_repo_name_here"
  
- name: Test cases
  block:

    - name: Failure case 1 - Invalid credentials
      block:
        - github_repo_collaborators:
            api_key: "{{GITHUB_API_KEY}}a"
            owner: "{{repo.owner}}"
            name: "{{repo.name}}"
            collaborators: "{{collaborators}}"
      rescue:
        - name: Failure case 1 - Invalid credentials
          assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == "Failed to authorise due to invalid credentials."

    - name: Failure case 2 - Invalid collaborators field
      block:
        - github_repo_collaborators:
            api_key: "{{GITHUB_API_KEY}}"
            owner: "{{repo.owner}}"
            name: "{{repo.name}}"
            collaborators:
              - username: this_will_fail
      rescue:
        - name: Failure case 2 - Failed request
          assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == "Collaborator objects must contain a username and role."

    - name: Success case
      block:
        - github_repo_collaborators:
            api_key: "{{GITHUB_API_KEY}}"
            owner: "{{repo.owner}}"
            name: "{{repo.name}}"
            collaborators: "{{collaborators}}"
          register: response

        - name: Success case
          assert:
            that:
              - response.collaborators is defined
              - response.collaborators|length == collaborators|length